### ISSUE TITLE
Rename Confusing Elements of Frontend

### ISSUE THREAD

**Issue by SamEGil00** [CSE437s/FL24-project-group-9#52]
On Planning page
------------------
Over each column, have a title. I.e. Suggested Semester VS Your Semester

Overall Frontend
----------------
Got lots of feedback on how titles were a bit confusing - i.e. difference between planner, dashboard, profile page.
People questioned why we have an uneditable dashboard page when our profile page already shows a student's full academic history

**Comment by NamanVer02** [comment]
Hi, I would love to contribute and work on this issue. Could you please assign it to me so I can start working on it ?
